# Semantic Commit bot: https://github.com/Ezard/semantic-prs

# Enable/disable creation of status checks
enabled: true

# Validate the PR title and all commit messages
titleAndCommits: true

# Allow merge commits (e.g. 'Merge branch "master" into fix/delete-all-tests')
allowMergeCommits: false

# Allow revert commits (e.g. 'Revert "fix: delete all tests"')
allowRevertCommits: true
